import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const centraNo2Bold = localFont({
  src: '../asserts/font/CentraNo2-Bold.ttf',
  variable: '--font-centra-bold'
})

const centraNo2Book = localFont({
  src: '../asserts/font/CentraNo2-Book.ttf',
  variable: '--font-centra-book'
})

const centraNo2Medium = localFont({
  src: '../asserts/font/CentraNo2-Medium.ttf',
  variable: '--font-centra-medium'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${centraNo2Bold.variable} ${centraNo2Book.variable} ${centraNo2Medium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
